[ci]
provider = "crow"
platform = "forgejo"
runtime = "nix"
runner = "codefloe-global"
workspace = true
publish_crates = true

[ci.pages]
repo = "caniko/nix-provenance"
token_secret = "CODEBERG_TOKEN"
