mod client;
mod state;

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;
use std::time::Duration;

use anyhow::{Context as _, Result};
use clap::Parser;
use provenance_core::password::{PasswordMarkerStore, read_password_file};

use client::TuwunelClient;
use state::State;

#[derive(Parser, Debug)]
#[command(
    name = "tuwunel-provision",
    about = "Declaratively provision Tuwunel Matrix users with auto-bootstrap",
    version
)]
struct Cli {
    /// Path to the JSON state file generated by the Nix module.
    #[arg(long)]
    state: PathBuf,

    /// Path to the admin token file (reads on startup, writes on bootstrap).
    #[arg(long)]
    admin_token_file: PathBuf,

    /// Path to the systemd credentials directory (%d at runtime).
    #[arg(long)]
    credential_dir: PathBuf,

    /// Path to the password marker directory.
    #[arg(long, default_value = "/var/lib/tuwunel/markers")]
    marker_dir: PathBuf,

    /// Seconds to wait for Tuwunel readiness before failing.
    #[arg(long, default_value_t = 30)]
    ready_timeout: u32,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    let raw = fs::read_to_string(&cli.state)
        .with_context(|| format!("reading state file {}", cli.state.display()))?;
    let state: State = serde_json::from_str(&raw)
        .with_context(|| format!("parsing state file {}", cli.state.display()))?;

    let base_url = format!("http://127.0.0.1:{}", state.port);
    let cred_dir = cli.credential_dir;
    let markers = PasswordMarkerStore::new(&cli.marker_dir);

    // Wait for server readiness (no auth needed).
    let probe_client = TuwunelClient::new_without_auth(&base_url)?;
    probe_client
        .wait_ready(cli.ready_timeout, Duration::from_secs(1))
        .context("waiting for tuwunel to be ready")?;

    // Bootstrap: resolve or create the admin token.
    let admin_token = bootstrap_admin_token(&state, &base_url, &cred_dir, &cli.admin_token_file)?;

    // Create authenticated client.
    let client = TuwunelClient::new(&base_url, &admin_token)?;

    // Provision each user.
    for (localpart, spec) in &state.users {
        let cred_path = cred_dir.join(&spec.credential_name);
        let password = match read_password_file(&cred_path) {
            Ok(pw) => pw,
            Err(e) => {
                eprintln!(
                    "tuwunel-provision: credential '{}' not found — skipping {localpart}: {e}",
                    spec.credential_name
                );
                continue;
            }
        };

        let marker_id = format!("tuwunel:user:{localpart}");
        if !markers.needs_update(&marker_id, &password)? {
            eprintln!("tuwunel-provision: {localpart} already up to date");
            continue;
        }

        let user_id = format!("@{localpart}:{}", state.server_name);
        eprintln!(
            "tuwunel-provision: provisioning {user_id} (admin={}, display={:?})",
            spec.admin, spec.display_name
        );

        client
            .create_or_update_user(
                &user_id,
                &password,
                spec.admin,
                spec.display_name.as_deref(),
            )
            .with_context(|| format!("provisioning {user_id}"))?;

        markers
            .commit(&marker_id, &password)
            .with_context(|| format!("committing password marker for {user_id}"))?;

        eprintln!("tuwunel-provision: {user_id} provisioned");
    }

    eprintln!("tuwunel-provision: done");
    Ok(())
}

fn bootstrap_admin_token(
    state: &State,
    base_url: &str,
    cred_dir: &PathBuf,
    admin_token_file: &PathBuf,
) -> Result<String> {
    // If the token file already has content, use it.
    if let Ok(token) = read_password_file(admin_token_file) {
        eprintln!("tuwunel-provision: admin token already present at {}", admin_token_file.display());
        return Ok(token);
    }

    eprintln!(
        "tuwunel-provision: no admin token found — bootstrapping first admin user"
    );

    let (username, spec) = state
        .users
        .iter()
        .find(|(_, spec)| spec.admin)
        .context(
            "no user with admin: true in state — cannot auto-bootstrap admin token",
        )?;

    let cred_path = cred_dir.join(&spec.credential_name);
    let password = read_password_file(&cred_path).with_context(|| {
        format!(
            "reading admin user '{username}' password from {}",
            cred_path.display()
        )
    })?;

    let client = TuwunelClient::new_without_auth(base_url)?;
    let user_id = format!("@{username}:{}", state.server_name);
    eprintln!("tuwunel-provision: registering admin user {user_id}");

    let token = client
        .register_admin(&user_id, &password)
        .with_context(|| format!("registering admin user {user_id}"))?;

    // Write token atomically with 0600 permissions.
    write_token_file(admin_token_file, &token)?;
    eprintln!(
        "tuwunel-provision: admin token written to {}",
        admin_token_file.display()
    );

    Ok(token)
}

fn write_token_file(path: &PathBuf, token: &str) -> Result<()> {
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, token)
        .with_context(|| format!("writing admin token to {}", tmp.display()))?;
    fs::set_permissions(&tmp, fs::Permissions::from_mode(0o600))
        .with_context(|| format!("setting permissions on {}", tmp.display()))?;
    fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} to {}", tmp.display(), path.display()))?;
    Ok(())
}
