mod client;
mod state;

use std::fs;
use std::os::unix::fs::OpenOptionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::thread::sleep;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use anyhow::{Context as _, Result, bail};
use clap::Parser;
use provenance_core::password::{PasswordMarkerStore, read_password_file};

use client::{TuwunelClient, registration_required};
use state::State;

#[derive(Parser, Debug)]
#[command(
    name = "tuwunel-provision",
    about = "Declaratively provision Tuwunel Matrix users with auto-bootstrap",
    version
)]
struct Cli {
    /// Path to the JSON state file generated by the Nix module.
    #[arg(long)]
    state: PathBuf,

    /// Path to the admin token file (reads on startup, writes on bootstrap).
    #[arg(long)]
    admin_token_file: PathBuf,

    /// Path to the systemd credentials directory (%d at runtime).
    #[arg(long)]
    credential_dir: PathBuf,

    /// Path to the password marker directory.
    #[arg(long, default_value = "/var/lib/tuwunel/markers")]
    marker_dir: PathBuf,

    /// Tuwunel config with public registration temporarily enabled.
    #[arg(long)]
    registration_bootstrap_open_config: Option<PathBuf>,

    /// Tuwunel config with public registration restored to the declared closed state.
    #[arg(long)]
    registration_bootstrap_closed_config: Option<PathBuf>,

    /// Mutable config path consumed by Tuwunel's SIGUSR2 reload command.
    #[arg(long)]
    registration_bootstrap_runtime_config: Option<PathBuf>,

    /// systemctl binary used to signal tuwunel.service.
    #[arg(long, default_value = "systemctl")]
    systemctl: PathBuf,

    /// systemd service to signal after writing the bootstrap runtime config.
    #[arg(long, default_value = "tuwunel.service")]
    tuwunel_service: String,

    /// Seconds to wait for Tuwunel readiness before failing.
    #[arg(long, default_value_t = 30)]
    ready_timeout: u32,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    let raw = fs::read_to_string(&cli.state)
        .with_context(|| format!("reading state file {}", cli.state.display()))?;
    let state: State = serde_json::from_str(&raw)
        .with_context(|| format!("parsing state file {}", cli.state.display()))?;

    let base_url = format!("http://127.0.0.1:{}", state.port);
    let registration_bootstrap = RegistrationBootstrap::from_cli(&cli)?;
    let cred_dir = cli.credential_dir;
    let markers = PasswordMarkerStore::new(&cli.marker_dir);

    // Wait for server readiness (no auth needed).
    let probe_client = TuwunelClient::new_without_auth(&base_url)?;
    probe_client
        .wait_ready(cli.ready_timeout, Duration::from_secs(1))
        .context("waiting for tuwunel to be ready")?;

    // Bootstrap: resolve or create the admin token.
    let admin_token = bootstrap_admin_token(
        &state,
        &base_url,
        &cred_dir,
        &cli.admin_token_file,
        registration_bootstrap.as_ref(),
    )?;

    // Create authenticated client.
    let client = TuwunelClient::new(&base_url, &admin_token)?;

    // Provision each user.
    for (localpart, spec) in &state.users {
        let cred_path = cred_dir.join(&spec.credential_name);
        let password = match read_password_file(&cred_path) {
            Ok(pw) => pw,
            Err(e) => {
                eprintln!(
                    "tuwunel-provision: credential '{}' not found — skipping {localpart}: {e}",
                    spec.credential_name
                );
                continue;
            }
        };

        let marker_id = format!("tuwunel:user:{localpart}");
        if !markers.needs_update(&marker_id, &password)? {
            eprintln!("tuwunel-provision: {localpart} already up to date");
            continue;
        }

        let user_id = format!("@{localpart}:{}", state.server_name);
        eprintln!(
            "tuwunel-provision: provisioning {user_id} (admin={}, display={:?})",
            spec.admin, spec.display_name
        );

        let provision_result = client.create_or_update_user(
            &user_id,
            &password,
            spec.admin,
            spec.display_name.as_deref(),
            false,
        );

        match provision_result {
            Ok(()) => {}
            Err(err) if registration_required(&err) => {
                let bootstrap = registration_bootstrap.as_ref().with_context(|| {
                    format!(
                        "provisioning {user_id} requires public registration, but registration \
                         bootstrap config paths were not supplied"
                    )
                })?;
                bootstrap
                    .with_registration_enabled(|| {
                        client.create_or_update_user(
                            &user_id,
                            &password,
                            spec.admin,
                            spec.display_name.as_deref(),
                            true,
                        )
                    })
                    .with_context(|| format!("provisioning {user_id}"))?;
            }
            Err(err) => return Err(err).with_context(|| format!("provisioning {user_id}")),
        }

        markers
            .commit(&marker_id, &password)
            .with_context(|| format!("committing password marker for {user_id}"))?;

        eprintln!("tuwunel-provision: {user_id} provisioned");
    }

    refresh_admin_token(&state, &client, &cred_dir, &cli.admin_token_file)?;

    for (name, room) in &state.rooms {
        // Private assistant rooms are created with the assistant's own Matrix
        // identity, so neither the provisioning admin nor a third-party bot
        // ever joins their encrypted conversation.
        if room.encrypted != room.creator.is_some() {
            bail!(
                "Matrix room {name} requires both creator and encrypted for private owner reconciliation"
            );
        }
        let creator_client = if let Some(creator) = &room.creator {
            if !room.alias.ends_with(&format!(":{}", state.server_name)) {
                bail!("Matrix room {name} alias does not belong to the provisioned server");
            }
            let user = state.users.get(creator).with_context(|| {
                format!("Matrix room {name} creator {creator} is not a provisioned user")
            })?;
            let password = read_password_file(cred_dir.join(&user.credential_name))
                .with_context(|| format!("reading credential for Matrix room {name} creator"))?;
            let token = probe_client
                .login_password_with_device(creator, &password, Some("TUWUNEL_PROVISION"))
                .with_context(|| format!("logging in Matrix room {name} creator"))?;
            Some(probe_client.with_token(&token))
        } else {
            None
        };
        let room_client = creator_client.as_ref().unwrap_or(&client);
        let reconciliation = (|| -> Result<()> {
            let room_id = match client
                .resolve_room_alias(&room.alias)
                .with_context(|| format!("resolving Matrix room {name} alias {}", room.alias))?
            {
                Some(room_id) => {
                    eprintln!("tuwunel-provision: room {name} already exists as {room_id}");
                    room_id
                }
                None if room.expected_room_id.is_some() => {
                    bail!(
                        "Matrix room {name} has a pinned ID but its alias is missing; refusing to create a replacement"
                    );
                }
                None => {
                    eprintln!(
                        "tuwunel-provision: creating room {name} alias {}",
                        room.alias
                    );
                    room_client
                        .create_room(
                            &room.alias,
                            room.name.as_deref(),
                            room.topic.as_deref(),
                            &room.invite,
                            room.encrypted,
                        )
                        .with_context(|| format!("creating Matrix room {name}"))?
                }
            };

            if let Some(expected) = &room.expected_room_id
                && &room_id != expected
            {
                bail!(
                    "Matrix room {name} alias resolves to {room_id}, not its declared room ID {expected}"
                );
            }

            if let Some(creator) = &room.creator {
                let creator_id = format!("@{creator}:{}", state.server_name);
                let present = room_client
                    .private_room_members(&room_id, &creator_id, &room.invite, room.encrypted)
                    .with_context(|| {
                        format!("checking Matrix room {name} before reconciling invites")
                    })?;
                for user_id in &room.invite {
                    if !present.contains(user_id) {
                        room_client
                            .invite_user_to_room(&room_id, user_id)
                            .with_context(|| format!("inviting {user_id} to Matrix room {name}"))?;
                    }
                }
                let verified = room_client
                    .private_room_members(&room_id, &creator_id, &room.invite, room.encrypted)
                    .with_context(|| {
                        format!("verifying Matrix room {name} after reconciliation")
                    })?;
                if room.invite.iter().any(|user| !verified.contains(user)) {
                    bail!("Matrix room {name} is missing an invited member after reconciliation");
                }
            } else {
                for user_id in &room.invite {
                    client
                        .invite_user_to_room(&room_id, user_id)
                        .with_context(|| format!("inviting {user_id} to Matrix room {name}"))?;
                }
            }
            Ok(())
        })();
        // The provisioning login is only needed for reconciliation. Revoke it
        // even if state verification or an invitation failed partway through.
        if let Some(creator_client) = &creator_client
            && let Err(err) = creator_client.logout()
        {
            if reconciliation.is_ok() {
                return Err(err).with_context(|| {
                    format!("logging out Matrix room {name} provisioning device")
                });
            }
            eprintln!(
                "tuwunel-provision: failed to log out Matrix room {name} provisioning device: {err:#}"
            );
        }
        reconciliation?;
    }

    eprintln!("tuwunel-provision: done");
    Ok(())
}

#[derive(Debug)]
struct RegistrationBootstrap {
    open_config: PathBuf,
    closed_config: PathBuf,
    runtime_config: PathBuf,
    systemctl: PathBuf,
    service: String,
}

impl RegistrationBootstrap {
    fn from_cli(cli: &Cli) -> Result<Option<Self>> {
        let provided = [
            cli.registration_bootstrap_open_config.is_some(),
            cli.registration_bootstrap_closed_config.is_some(),
            cli.registration_bootstrap_runtime_config.is_some(),
        ];
        if provided.iter().all(|value| !value) {
            return Ok(None);
        }
        if !provided.iter().all(|value| *value) {
            anyhow::bail!(
                "--registration-bootstrap-open-config, --registration-bootstrap-closed-config, \
                 and --registration-bootstrap-runtime-config must be supplied together"
            );
        }

        Ok(Some(Self {
            open_config: cli.registration_bootstrap_open_config.clone().unwrap(),
            closed_config: cli.registration_bootstrap_closed_config.clone().unwrap(),
            runtime_config: cli.registration_bootstrap_runtime_config.clone().unwrap(),
            systemctl: cli.systemctl.clone(),
            service: cli.tuwunel_service.clone(),
        }))
    }

    fn with_registration_enabled<T>(&self, mut f: impl FnMut() -> Result<T>) -> Result<T> {
        let result = (|| {
            self.reload_from(&self.open_config, "enable public registration")?;
            // SIGUSR2 schedules an asynchronous admin command. A fixed delay
            // does not prove registration has opened, especially on a busy VM.
            // Only the explicit pre-mutation refusal is safe to retry;
            // transport errors could mean registration already succeeded.
            let mut result = f();
            for _ in 1..20 {
                if !result.as_ref().err().is_some_and(|err| {
                    err.chain()
                        .any(|cause| cause.to_string() == "registration_disabled")
                }) {
                    break;
                }
                sleep(Duration::from_millis(250));
                result = f();
            }
            result
        })();
        // Even a failed signal can follow writing the open runtime config.
        let restore = self.reload_from(&self.closed_config, "disable public registration");

        match (result, restore) {
            (Ok(value), Ok(())) => Ok(value),
            (Err(err), Ok(())) => Err(err),
            (Ok(_), Err(restore_err)) => Err(restore_err).context(
                "provisioning succeeded, but restoring disabled registration failed; \
                 manual intervention is required before leaving the host exposed",
            ),
            (Err(err), Err(restore_err)) => Err(err).context(format!(
                "provisioning failed, and restoring disabled registration also failed: {restore_err:#}"
            )),
        }
    }

    fn reload_from(&self, source: &PathBuf, reason: &str) -> Result<()> {
        let contents = fs::read(source)
            .with_context(|| format!("reading tuwunel {reason} config {}", source.display()))?;
        atomic_write_0644(&self.runtime_config, &contents).with_context(|| {
            format!(
                "writing tuwunel runtime bootstrap config {}",
                self.runtime_config.display()
            )
        })?;

        eprintln!(
            "tuwunel-provision: {reason} via {} and SIGUSR2 to {}",
            self.runtime_config.display(),
            self.service
        );
        let status = Command::new(&self.systemctl)
            .arg("kill")
            .arg("--signal=SIGUSR2")
            .arg("--kill-who=main")
            .arg(&self.service)
            .status()
            .with_context(|| format!("running {}", self.systemctl.display()))?;
        if !status.success() {
            anyhow::bail!(
                "{} kill command failed with status {status}",
                self.systemctl.display()
            );
        }

        // Tuwunel runs admin_signal_execute asynchronously after SIGUSR2.
        sleep(Duration::from_millis(750));
        Ok(())
    }
}

fn refresh_admin_token(
    state: &State,
    client: &TuwunelClient,
    cred_dir: &Path,
    admin_token_file: &Path,
) -> Result<()> {
    let Some(localpart) = state.admin_token_user.as_deref() else {
        return Ok(());
    };

    let spec = state
        .users
        .get(localpart)
        .with_context(|| format!("admin_token_user '{localpart}' is not present in users"))?;
    if !spec.admin {
        anyhow::bail!("admin_token_user '{localpart}' must reference a user with admin: true");
    }

    let cred_path = cred_dir.join(&spec.credential_name);
    let password = read_password_file(&cred_path).with_context(|| {
        format!(
            "reading admin token user '{localpart}' password from {}",
            cred_path.display()
        )
    })?;

    let token = client
        .login_password(localpart, &password)
        .with_context(|| format!("logging in admin token user '{localpart}'"))?;
    write_token_file(admin_token_file, &token)?;
    eprintln!(
        "tuwunel-provision: admin token refreshed from {localpart} at {}",
        admin_token_file.display()
    );
    Ok(())
}

fn bootstrap_admin_token(
    state: &State,
    base_url: &str,
    cred_dir: &Path,
    admin_token_file: &PathBuf,
    registration_bootstrap: Option<&RegistrationBootstrap>,
) -> Result<String> {
    // If the token file already has content, use it.
    if let Ok(token) = read_password_file(admin_token_file) {
        eprintln!(
            "tuwunel-provision: admin token already present at {}",
            admin_token_file.display()
        );
        return Ok(token);
    }

    eprintln!("tuwunel-provision: no admin token found — bootstrapping first admin user");

    let (username, spec) = state
        .users
        .iter()
        .find(|(_, spec)| spec.admin)
        .context("no user with admin: true in state — cannot auto-bootstrap admin token")?;

    let cred_path = cred_dir.join(&spec.credential_name);
    let password = read_password_file(&cred_path).with_context(|| {
        format!(
            "reading admin user '{username}' password from {}",
            cred_path.display()
        )
    })?;

    let client = TuwunelClient::new_without_auth(base_url)?;
    let user_id = format!("@{username}:{}", state.server_name);
    eprintln!("tuwunel-provision: registering admin user {user_id}");

    let register = || {
        client
            .register_admin(&user_id, &password)
            .with_context(|| format!("registering admin user {user_id}"))
    };
    let token = match register() {
        Ok(token) => token,
        Err(err) if registration_required(&err) => {
            let bootstrap = registration_bootstrap.with_context(|| {
                format!(
                    "registering admin user {user_id} requires public registration, but \
                     registration bootstrap config paths were not supplied"
                )
            })?;
            bootstrap.with_registration_enabled(register)?
        }
        Err(err) => return Err(err),
    };

    // Write token atomically with 0600 permissions.
    write_token_file(admin_token_file, &token)?;
    eprintln!(
        "tuwunel-provision: admin token written to {}",
        admin_token_file.display()
    );

    Ok(token)
}

fn atomic_write_0644(path: &Path, contents: &[u8]) -> Result<()> {
    atomic_write(path, contents, 0o644)
}

fn write_token_file(path: &Path, token: &str) -> Result<()> {
    atomic_write(path, token.as_bytes(), 0o600)
}

fn atomic_write(path: &Path, contents: &[u8], mode: u32) -> Result<()> {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|err| anyhow::anyhow!("clock before Unix epoch: {err}"))?
        .as_nanos();
    let tmp = path.with_extension(format!("tmp.{}.{}", std::process::id(), stamp));
    let result: Result<()> = (|| {
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(mode)
            .open(&tmp)
            .with_context(|| format!("writing {}", tmp.display()))?;
        use std::io::Write as _;
        file.write_all(contents)
            .with_context(|| format!("writing {}", tmp.display()))?;
        file.sync_all()
            .with_context(|| format!("syncing {}", tmp.display()))?;
        fs::rename(&tmp, path)
            .with_context(|| format!("renaming {} to {}", tmp.display(), path.display()))?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&tmp);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::Cell;
    use std::os::unix::fs::PermissionsExt;

    fn bootstrap_fixture(dir: &Path) -> RegistrationBootstrap {
        let systemctl = dir.join("systemctl");
        fs::write(&systemctl, "#!/usr/bin/env sh\nexit 0\n").unwrap();
        fs::set_permissions(&systemctl, fs::Permissions::from_mode(0o700)).unwrap();
        let fixture = RegistrationBootstrap {
            open_config: dir.join("open.toml"),
            closed_config: dir.join("closed.toml"),
            runtime_config: dir.join("runtime.toml"),
            systemctl,
            service: "fixture.service".into(),
        };
        fs::write(&fixture.open_config, "allow_registration = true").unwrap();
        fs::write(&fixture.closed_config, "allow_registration = false").unwrap();
        fixture
    }

    #[test]
    fn delayed_registration_reload_succeeds_and_restores_closed_config() {
        let dir = tempfile::tempdir().unwrap();
        let fixture = bootstrap_fixture(dir.path());
        let attempts = Cell::new(0);
        let result = fixture.with_registration_enabled(|| {
            attempts.set(attempts.get() + 1);
            if attempts.get() < 3 {
                Err(anyhow::anyhow!("registration_disabled").context("registering fixture"))
            } else {
                Ok("fixture-token")
            }
        });
        assert_eq!(result.unwrap(), "fixture-token");
        assert_eq!(
            fs::read(&fixture.runtime_config).unwrap(),
            fs::read(&fixture.closed_config).unwrap()
        );
    }

    #[test]
    fn ambiguous_registration_failure_is_not_retried_and_restores_closed_config() {
        let dir = tempfile::tempdir().unwrap();
        let fixture = bootstrap_fixture(dir.path());
        let attempts = Cell::new(0);
        let result: Result<()> = fixture.with_registration_enabled(|| {
            attempts.set(attempts.get() + 1);
            Err(anyhow::anyhow!(
                "connection lost after registration request"
            ))
        });
        assert!(result.is_err());
        assert_eq!(attempts.get(), 1);
        assert_eq!(
            fs::read(&fixture.runtime_config).unwrap(),
            fs::read(&fixture.closed_config).unwrap()
        );
    }

    #[test]
    fn registration_never_opens_fails_within_bound_and_restores_closed_config() {
        let dir = tempfile::tempdir().unwrap();
        let fixture = bootstrap_fixture(dir.path());
        let attempts = Cell::new(0);
        let result: Result<()> = fixture.with_registration_enabled(|| {
            attempts.set(attempts.get() + 1);
            Err(anyhow::anyhow!("registration_disabled"))
        });
        assert!(registration_required(&result.unwrap_err()));
        assert!(attempts.get() > 1 && attempts.get() <= 20);
        assert_eq!(
            fs::read(&fixture.runtime_config).unwrap(),
            fs::read(&fixture.closed_config).unwrap()
        );
    }

    #[test]
    fn failed_open_signal_still_restores_closed_runtime_config() {
        let dir = tempfile::tempdir().unwrap();
        let fixture = bootstrap_fixture(dir.path());
        fs::write(&fixture.systemctl, "#!/usr/bin/env sh\nexit 1\n").unwrap();
        let result: Result<()> = fixture.with_registration_enabled(|| {
            panic!("must not register after failing to signal the server");
        });
        assert!(result.is_err());
        assert_eq!(
            fs::read(&fixture.runtime_config).unwrap(),
            fs::read(&fixture.closed_config).unwrap()
        );
    }
}
