name: ci

on:
  push:
    branches: [trunk]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    runs-on: atlas-nix-trusted
    steps:
      - uses: https://code.forgejo.org/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: nix flake check --keep-going --print-build-logs

  push-cache:
    needs: [flake-check]
    if: ${{ github.ref == 'refs/heads/trunk' }}
    runs-on: atlas-nix-trusted
    steps:
      - uses: https://code.forgejo.org/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: nix run .#push-cache
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
