//! Declarative state schema.
//!
//! The state file is a JSON document with four top-level maps — `groups`,
//! `roles`, `users`, and `clients` — mirroring the entity types Rauthy's admin
//! API exposes to an API key. Each entity carries a `present` flag (default
//! `true`); setting it `false` deletes the entity if it exists.
//!
//! This is the analogue of kanidm-provision's `state.json`, adapted to
//! Rauthy's data model. There is intentionally **no** orphan auto-removal:
//! Rauthy has no tracking-group equivalent, so the only way to delete an
//! entity is to declare it with `present = false`.

use std::collections::BTreeMap;

use provenance_core::serde_ext::default_true;
use serde::Deserialize;

fn default_language() -> String {
    "en".to_string()
}

fn default_user_scopes() -> Vec<String> {
    vec![
        "openid".to_string(),
        "profile".to_string(),
        "email".to_string(),
    ]
}

fn default_flows() -> Vec<String> {
    vec![
        "authorization_code".to_string(),
        "refresh_token".to_string(),
    ]
}

/// Top-level declarative state. Keys are the natural identifier for each
/// entity type (group name, role name, user email, client id).
#[derive(Debug, Default, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct State {
    #[serde(default)]
    pub groups: BTreeMap<String, GroupSpec>,
    #[serde(default)]
    pub roles: BTreeMap<String, RoleSpec>,
    /// Keyed by the user's primary email address.
    #[serde(default)]
    pub users: BTreeMap<String, UserSpec>,
    /// Keyed by the OIDC client id.
    #[serde(default)]
    pub clients: BTreeMap<String, ClientSpec>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GroupSpec {
    #[serde(default = "default_true")]
    pub present: bool,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RoleSpec {
    #[serde(default = "default_true")]
    pub present: bool,
}

/// A Rauthy user. Created passwordless: no credential is set and no email is
/// sent. When Rauthy is wired to an upstream OIDC provider (e.g. kanidm) with
/// "Auto-Link User" enabled, a passwordless local user whose email matches the
/// upstream identity is auto-linked on first federated login.
///
/// `given_name`, `family_name`, and `language` are applied only at creation —
/// they are *not* re-enforced on update, so federated profile-claim sync from
/// the upstream IdP is never fought. Updates reconcile `roles` and `groups`
/// only (the authorization-relevant attributes).
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UserSpec {
    #[serde(default = "default_true")]
    pub present: bool,
    #[serde(default)]
    pub given_name: Option<String>,
    #[serde(default)]
    pub family_name: Option<String>,
    #[serde(default = "default_language")]
    pub language: String,
    #[serde(default)]
    pub roles: Vec<String>,
    #[serde(default)]
    pub groups: Vec<String>,
    /// On user CREATION only, ask Rauthy to email the user a set-password link
    /// (Rauthy's `request_reset` flow). A no-op when the user already exists, so
    /// at most one email is ever sent per user. Use for external users who have
    /// no upstream IdP and must set a native Rauthy password.
    #[serde(default)]
    pub send_password_email: bool,
    /// Where Rauthy redirects the user after they finish setting their password.
    /// Point this at the consuming app's login-initiating route (e.g.
    /// `https://app.example.com/login`), NOT a raw OIDC callback. Only meaningful
    /// when `send_password_email` is true.
    #[serde(default)]
    pub password_email_redirect_uri: Option<String>,
}

/// An OIDC client (relying party). After creation the confidential client's
/// secret is auto-generated by Rauthy; this tool does not manage the secret
/// value (retrieve it via the Admin UI or `POST /clients/{id}/secret`).
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientSpec {
    #[serde(default = "default_true")]
    pub present: bool,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default = "default_true")]
    pub confidential: bool,
    #[serde(default)]
    pub redirect_uris: Vec<String>,
    #[serde(default)]
    pub post_logout_redirect_uris: Vec<String>,
    #[serde(default)]
    pub allowed_origins: Vec<String>,
    #[serde(default = "default_user_scopes")]
    pub scopes: Vec<String>,
    #[serde(default = "default_user_scopes")]
    pub default_scopes: Vec<String>,
    #[serde(default = "default_flows")]
    pub flows_enabled: Vec<String>,
    /// Enable PKCE (S256). Strongly recommended; required for public clients.
    #[serde(default = "default_true")]
    pub enable_pkce: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_minimal_state() {
        let s: State = serde_json::from_str("{}").unwrap();
        assert!(s.users.is_empty());
        assert!(s.groups.is_empty());
    }

    #[test]
    fn user_defaults_present_and_language() {
        let s: State =
            serde_json::from_str(r#"{ "users": { "a@example.com": { "roles": ["admin"] } } }"#)
                .unwrap();
        let u = &s.users["a@example.com"];
        assert!(u.present);
        assert_eq!(u.language, "en");
        assert_eq!(u.roles, vec!["admin".to_string()]);
        assert!(u.groups.is_empty());
    }

    #[test]
    fn client_defaults() {
        let s: State = serde_json::from_str(
            r#"{ "clients": { "app": { "redirect_uris": ["https://app/cb"] } } }"#,
        )
        .unwrap();
        let c = &s.clients["app"];
        assert!(c.present);
        assert!(c.confidential);
        assert!(c.enable_pkce);
        assert_eq!(c.scopes, vec!["openid", "profile", "email"]);
        assert_eq!(c.flows_enabled, vec!["authorization_code", "refresh_token"]);
    }
}
