//! stalwart016-provision — recovery-mode provisioner for Stalwart Mail Server 0.16.
//!
//! Replaces the `writeShellApplication` shell script in the `stalwart016` NixOS
//! module with a robust Rust binary.  The lifecycle is:
//!
//! 1. Read a JSON config file (generated at Nix eval time) for all static settings.
//! 2. Check marker files to decide whether migration and/or registry plans need
//!    applying.  If nothing is pending, exit 0.
//! 3. Optionally probe the PostgreSQL store to guard against a silently-recreated DB.
//! 4. Start stalwart in recovery mode, wait for readiness, apply plans, write
//!    markers, query objects for evidence, and exit (killing the recovery process).

mod apply;
mod error;
mod health;
mod markers;
mod recovery;

use std::fmt;
use std::fs;
use std::net::TcpStream;
use std::path::PathBuf;
use std::time::Duration;

use anyhow::{Context, Result, bail};
use chrono::Utc;
use clap::Parser;
use serde::Deserialize;

/// CLI entrypoint for the stalwart016 provisioner.
///
/// Static settings (paths, hostname, timeouts) come from a JSON config file
/// generated at Nix eval time.  Runtime-only paths — the credentials inside
/// systemd's `$CREDENTIALS_DIRECTORY` — are passed as separate CLI args so
/// their store-path-free runtime resolution is preserved.
#[derive(Parser, Debug)]
#[command(
    name = "stalwart016-provision",
    about = "Stalwart 0.16 recovery-mode provisioner",
    version
)]
struct Cli {
    /// Path to the JSON config file generated by the Nix module.
    #[arg(long)]
    config: PathBuf,

    /// Path to the recovery admin password file inside systemd's credentials
    /// directory (e.g. `%d/recovery_admin_password`).
    #[arg(long)]
    recovery_password_file: PathBuf,

    /// Path to the PG password file inside systemd's credentials directory
    /// (only needed when store health check is enabled).
    #[arg(long)]
    pg_password_file: Option<PathBuf>,
}

/// Static settings generated by the Nix module at eval time.
#[derive(Debug, Deserialize)]
struct Config {
    #[serde(rename = "migration_marker_file")]
    migration_marker: PathBuf,
    #[serde(rename = "registry_marker_file")]
    registry_marker: PathBuf,
    #[serde(rename = "legacy_marker_file")]
    legacy_marker: PathBuf,
    #[serde(rename = "generated_plan_file")]
    plan: PathBuf,

    #[serde(default)]
    migration_apply_files: Vec<PathBuf>,

    #[serde(rename = "stalwart_binary")]
    stalwart_bin: PathBuf,
    #[serde(rename = "stalwart_config")]
    stalwart_cfg: PathBuf,
    hostname: String,
    #[serde(rename = "stalwart_cli_binary")]
    cli_bin: PathBuf,

    #[serde(default = "default_recovery_url")]
    recovery_url: String,
    #[serde(default = "default_admin_username")]
    recovery_admin_username: String,

    #[serde(default = "default_startup_attempts")]
    startup_attempts: u32,
    #[serde(
        default = "default_startup_interval",
        deserialize_with = "deserialize_f64"
    )]
    startup_interval_secs: f64,

    #[serde(default = "default_query_output_dir")]
    query_output_dir: PathBuf,
    #[serde(default = "default_query_objects")]
    query_objects: Vec<String>,

    #[serde(default)]
    continue_on_error: bool,

    #[serde(default)]
    require_verified_backup_sentinel: Option<PathBuf>,

    #[serde(default)]
    store_health_check: bool,
    #[serde(default = "default_probe_table")]
    probe_table: String,

    #[serde(default)]
    psql_binary: Option<PathBuf>,
    #[serde(default = "default_pg_host")]
    pg_host: String,
    #[serde(default = "default_pg_port")]
    pg_port: u16,
    #[serde(default = "default_pg_user")]
    pg_user: String,
    #[serde(default = "default_pg_database")]
    pg_database: String,
}

/// Deserialize an f64 from either a JSON number or a string.
fn deserialize_f64<'de, D: serde::Deserializer<'de>>(d: D) -> Result<f64, D::Error> {
    use serde::de;
    struct F64OrString;
    impl<'de> de::Visitor<'de> for F64OrString {
        type Value = f64;
        fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
            f.write_str("a float or a string containing a float")
        }
        fn visit_f64<E: de::Error>(self, v: f64) -> Result<f64, E> {
            Ok(v)
        }
        fn visit_u64<E: de::Error>(self, v: u64) -> Result<f64, E> {
            Ok(v as f64)
        }
        fn visit_i64<E: de::Error>(self, v: i64) -> Result<f64, E> {
            Ok(v as f64)
        }
        fn visit_str<E: de::Error>(self, v: &str) -> Result<f64, E> {
            v.parse().map_err(de::Error::custom)
        }
    }
    d.deserialize_any(F64OrString)
}

fn default_recovery_url() -> String {
    "http://127.0.0.1:8080".into()
}
fn default_admin_username() -> String {
    "admin".into()
}
fn default_startup_attempts() -> u32 {
    120
}
fn default_startup_interval() -> f64 {
    0.25
}
fn default_query_output_dir() -> PathBuf {
    PathBuf::from("/var/lib/stalwart016")
}
fn default_query_objects() -> Vec<String> {
    vec!["NetworkListener".into()]
}
fn default_probe_table() -> String {
    "f".into()
}
fn default_pg_host() -> String {
    "127.0.0.1".into()
}
fn default_pg_port() -> u16 {
    5432
}
fn default_pg_user() -> String {
    "stalwart".into()
}
fn default_pg_database() -> String {
    "stalwart".into()
}

/// Struct tracking what work is pending.
struct Pending {
    migration: bool,
    registry: bool,
}

/// Determine migration and registry pending state from marker files.
fn check_pending(cfg: &Config) -> Result<Pending> {
    let migration = if !cfg.migration_apply_files.is_empty() {
        markers::read_migration_marker(&cfg.migration_marker)?.is_none()
    } else {
        false
    };

    let registry = {
        let current_plan = cfg.plan.display().to_string();
        match markers::read_registry_marker(&cfg.registry_marker)? {
            Some(m) => m.generated_plan != current_plan,
            None => true,
        }
    };

    Ok(Pending {
        migration,
        registry,
    })
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let cfg: Config = serde_json::from_str(
        &fs::read_to_string(&cli.config)
            .context(format!("reading config file {}", cli.config.display()))?,
    )
    .context("parsing config JSON")?;

    // ── Create marker directories ────────────────────────────
    for dir in [cfg.migration_marker.parent(), cfg.registry_marker.parent()]
        .into_iter()
        .flatten()
    {
        fs::create_dir_all(dir).context(format!("creating marker directory {}", dir.display()))?;
    }

    // ── Legacy marker promotion ──────────────────────────────
    if markers::promote_legacy_marker(&cfg.legacy_marker, &cfg.migration_marker)? {
        eprintln!(
            "stalwart016-provision: promoted legacy marker {} -> {}",
            cfg.legacy_marker.display(),
            cfg.migration_marker.display()
        );
    }

    // ── Check pending ────────────────────────────────────────
    let mut pending = check_pending(&cfg)?;

    // ── Store health check ───────────────────────────────────
    if !pending.migration
        && !pending.registry
        && cfg.store_health_check
        && let (Some(psql_bin), Some(pg_pw_file)) = (&cfg.psql_binary, &cli.pg_password_file)
    {
        match health::probe_store(
            psql_bin,
            &cfg.pg_host,
            cfg.pg_port,
            &cfg.pg_user,
            &cfg.pg_database,
            pg_pw_file,
            &cfg.probe_table,
        )? {
            health::StoreHealth::Ok => {}
            health::StoreHealth::Unreachable => {
                eprintln!(
                    "stalwart016-provision: store health check skipped \
                         (PostgreSQL unreachable — may be restarting)"
                );
            }
            health::StoreHealth::TableMissing => {
                eprintln!(
                    "stalwart016-provision: store health check failed (table '{}' \
                         missing) — forcing recovery mode",
                    cfg.probe_table
                );
                let _ = fs::remove_file(&cfg.registry_marker);
                pending.registry = true;
            }
            health::StoreHealth::CredentialUnreadable => {
                eprintln!(
                    "stalwart016-provision: store health check skipped \
                         (PG credential not readable)"
                );
            }
        }
    }

    // ── Early exit if nothing pending ────────────────────────
    if !pending.migration && !pending.registry {
        eprintln!("stalwart016-provision: migration and registry already current; nothing to do");
        return Ok(());
    }

    // ── Backup sentinel check ────────────────────────────────
    if let Some(ref sentinel) = cfg.require_verified_backup_sentinel {
        let meta = fs::metadata(sentinel)
            .context(format!("reading backup sentinel {}", sentinel.display()))?;
        if meta.len() == 0 {
            bail!(error::ProvisionError::MissingBackupSentinel(
                sentinel.clone()
            ));
        }
    }

    // ── Read recovery admin password ─────────────────────────
    let recovery_password =
        provenance_core::password::read_password_file(&cli.recovery_password_file).map_err(
            |_| error::ProvisionError::MissingRecoveryPassword(cli.recovery_password_file.clone()),
        )?;

    // ── Port conflict check ──────────────────────────────────
    {
        let stripped = cfg
            .recovery_url
            .strip_prefix("http://")
            .unwrap_or(&cfg.recovery_url);
        let parts: Vec<&str> = stripped.splitn(2, ':').collect();
        let host = parts[0];
        let port: u16 = parts
            .get(1)
            .and_then(|s| s.trim_end_matches('/').parse().ok())
            .unwrap_or(8080);
        let addr = format!("{host}:{port}");
        if TcpStream::connect_timeout(&addr.parse()?, Duration::from_secs(1)).is_ok() {
            bail!(error::ProvisionError::PortConflict);
        }
    }

    // ── Start recovery server ────────────────────────────────
    let recovery_admin = format!("{}:{}", cfg.recovery_admin_username, recovery_password);
    let _recovery = recovery::RecoveryServer::start(
        &cfg.stalwart_bin,
        &cfg.stalwart_cfg,
        &recovery_admin,
        &cfg.hostname,
    )?;

    // ── Wait for recovery listener ready ─────────────────────
    recovery::RecoveryServer::wait_ready(
        &cfg.cli_bin,
        &cfg.recovery_url,
        &cfg.recovery_admin_username,
        &recovery_password,
        "NetworkListener",
        cfg.startup_attempts,
        Duration::from_secs_f64(cfg.startup_interval_secs),
    )?;

    // ── Apply migration documents ────────────────────────────
    if pending.migration {
        for file in &cfg.migration_apply_files {
            eprintln!(
                "stalwart016-provision: applying migration {}",
                file.display()
            );
            let result = recovery::apply_document(
                &cfg.cli_bin,
                &cfg.recovery_url,
                &cfg.recovery_admin_username,
                &recovery_password,
                file,
                cfg.continue_on_error,
            )?;
            if result.exit_code != 0 {
                let detail = result.stderr.lines().last().unwrap_or("<no output>");
                bail!(error::ProvisionError::ApplyFailed {
                    file: file.display().to_string(),
                    detail: detail.to_string(),
                });
            }
        }

        markers::write_migration_marker(
            &cfg.migration_marker,
            &markers::MigrationMarker {
                completed_at: Utc::now().to_rfc3339(),
                migration_files: cfg
                    .migration_apply_files
                    .iter()
                    .map(|p| p.display().to_string())
                    .collect(),
            },
        )?;
        eprintln!(
            "stalwart016-provision: migration complete — wrote {}",
            cfg.migration_marker.display()
        );
    } else {
        eprintln!(
            "stalwart016-provision: migration apply already completed ({} exists); skipping",
            cfg.migration_marker.display()
        );
    }

    // ── Apply registry plan ──────────────────────────────────
    if pending.registry {
        let plan_result = apply::apply_plan(
            &cfg.cli_bin,
            &cfg.recovery_url,
            &cfg.recovery_admin_username,
            &recovery_password,
            &cfg.plan,
            cfg.continue_on_error,
        )?;

        if plan_result.success {
            markers::write_registry_marker(
                &cfg.registry_marker,
                &markers::RegistryMarker {
                    completed_at: Utc::now().to_rfc3339(),
                    generated_plan: cfg.plan.display().to_string(),
                },
            )?;
            eprintln!(
                "stalwart016-provision: registry plan applied ({} created, {} updated, \
                 {} destroyed) — wrote {}",
                plan_result.created,
                plan_result.updated,
                plan_result.destroyed,
                cfg.registry_marker.display()
            );
        } else {
            for err in &plan_result.errors {
                eprintln!("stalwart016-provision: registry apply error: {err}");
            }
            if let Some(err_detail) = plan_result.errors.first() {
                bail!(error::ProvisionError::ApplyFailed {
                    file: cfg.plan.display().to_string(),
                    detail: err_detail.clone(),
                });
            }
        }
    } else {
        eprintln!("stalwart016-provision: generated registry plan already current; skipping");
    }

    // ── Query objects for evidence ───────────────────────────
    for object_type in &cfg.query_objects {
        match recovery::query_object(
            &cfg.cli_bin,
            &cfg.recovery_url,
            &cfg.recovery_admin_username,
            &recovery_password,
            object_type,
        ) {
            Ok(data) => {
                if let Err(e) =
                    recovery::write_query_output(&cfg.query_output_dir, object_type, &data)
                {
                    eprintln!(
                        "stalwart016-provision: warning — failed to write query output \
                         for {object_type}: {e}"
                    );
                }
            }
            Err(e) => {
                eprintln!("stalwart016-provision: warning — query {object_type} failed: {e}");
            }
        }
    }

    // ── Exit (RecoveryServer Drop kills stalwart) ───────────
    Ok(())
}
