[book]
title = "nix-provenance Documentation"
authors = ["Can H. Tartanoglu"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/nix-provenance/"
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/caniko/nix-provenance"
